wire up dealer locator for mackrtucks aus
hlxsites/vg-macktrucks-com-au pull request #1
Opened 2023-09-27 12:50 UTC by Lakshmishri

Fix #439

Test URLs:
- Before: https://main--vg-macktrucks-com--hlxsites.hlx.page/
- After: https://439-dealer-locator-au--vg-macktrucks-com--hlxsites.hlx.page/

2023-11-07 14:17 UTC, jonatan-lledo-netcentric approved these changes

2023-11-08 11:21 UTC, jonatan-lledo-netcentric requested changes

2023-11-08 11:21 UTC, jonatan-lledo-netcentric commented on blocks/dealer-locator/dealer-locator.css
> +/* @media (max-width: 992px) {
please, remove the commented code. Thanks

2023-11-10 12:25 UTC, jonatan-lledo-netcentric approved these changes

2023-11-10 15:23 UTC, manuel-vara approved these changes

2023-11-10 15:44 UTC, merged